### ISSUE TITLE
怎样设置chosen的高度？

### ISSUE THREAD

**Issue by shaohao2014** [amazeui/chosen#1]
如题目。

**Comment by minwe** [comment]
下拉框的高度？

```css
.chosen-container .chosen-results {
   max-width: 180px;
}
```
